name: Build iJIT App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List Files (The Eyes Step)
        run: ls -R
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npx expo export --platform ios --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: iJIT-Build
          path: dist/
